### ISSUE TITLE
create-keypair fails with missing region

### ISSUE THREAD

**Issue by cellistigs** [lime-green/remote-docker-aws#20]
When going through the Setup steps in the readme file, I encountered the following error: 
![Screen Shot 2020-12-19 at 12 25 23 PM](https://user-images.githubusercontent.com/29405444/102695428-51cb4100-41f5-11eb-9dbb-21cd392801d3.png)

I assumed this was an error where remote-docker-aws was unable to read my .aws/config file- I confirmed that this file had correctly saved the profile created in step one, and that the region parameter was correctly formatted.

I was able to successfully upload a key pair by explicitly declaring the aws region with `export AWS_REGION=us-east-1` from the command line and rerunning the third step. Continuing with setup I confirmed that the cloudformation stack successfully built on my AWS account. 

System details: I am running GNU bash 3.2.57(1)-release (x86_64-apple-darwin17) on MacOS High Sierra version 10.13.6

This is a super cool project, thank you for building!

**Comment by lime-green** [comment]
@cellistigs Thanks for the detailed bug report!

I've merged and released 2.2.0 which includes a fix for this.

Happy new year! 🎉
